
-- 2. CRIAR TABELA
CREATE TABLE [dbo].[Match](
	[Id] [uniqueidentifier] NOT NULL,
	[UsuarioCurtiu] [varchar](100) NOT NULL,
	[UsuarioCurtido] [varchar](100) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO